### ISSUE TITLE
ModuleNotFoundError: No module named 'testapp'

### ISSUE THREAD

**Issue by vladiuz1** [sh4nks/flask-plugins#23]
code @ main.py:

```py
from flask import Flask, Response, session, render_template, jsonify, request, redirect, make_response, url_for
from flask_plugins import PluginManager
app = Flask(__name__, static_url_path='/public', static_folder='public')
plugin_manager = PluginManager()
plugin_manager.init_app(app)
```

error message:

```
Traceback (most recent call last):
  File "main.py", line 57, in <module>
    plugin_manager.init_app(app)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_plugins/__init__.py", line 245, in init_app
    self.setup_plugins()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_plugins/__init__.py", line 331, in setup_plugins
    for plugin in itervalues(self.plugins):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_plugins/__init__.py", line 259, in plugins
    self.load_plugins()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_plugins/__init__.py", line 269, in load_plugins
    for plugin_name, plugin_package in iteritems(self.find_plugins()):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_plugins/__init__.py", line 306, in find_plugins
    tmp = importlib.import_module(plugin)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'testapp'
```

Seems that plugin_manager.init_app is trying to import host application module. But my app doesn't have a setup.py, nor there is a need for it.. Can I use it in a standalone  app without setup.py installation?

**Comment by gnubyte** [comment]
This exact code works for me. The stacktrace suggests there is an issue with a package related to Bootstrap.

Can you post your requirements.txt and the imports for your plugin? I'll take a look at that as well.

```from flask import Flask, Response, session, render_template, jsonify, request, redirect, make_response, url_for
from flask_plugins import PluginManager
app = Flask(__name__, static_url_path='/public', static_folder='public')
plugin_manager = PluginManager()
plugin_manager.init_app(app)


@app.route('/')
def index():
    return render_template('index.html')

if __name__ == "__main__":
    app.run(port=5000, debug=True)
```

**Comment by vladiuz1** [comment]
requirements.txt

```
google-api-python-client==1.7.11
google-auth==1.14.0
google-auth-oauthlib==0.3.0
google-auth-httplib2==0.0.3
Flask==1.0.2
Flask-Session
Flask-Limiter
validators
google-cloud-datastore==1.7.3
google-cloud-storage==1.15.0
google-cloud-bigquery==1.10
requests[socks]
humanize
ipaddress
sendgrid
ruamel.yaml
extraction
html-sanitizer==1.7.2
PyTelegramBotAPI
YURL
grpcio
tldextract
dnspython
awesome-slugify==1.6.5
gunicorn==20.0.4
chardet
flask-plugins
```

my plugin's __init__.py is very simple... its just a test:

```python
from flask import flash, Blueprint, render_template, render_template_string, jsonify, request
from flask_plugins import connect_event

__plugin__ = "PyIP"
__version__ = "0.1.0"

ip = Blueprint("ip", __name__, template_folder="templates")

@ip.route("/")
def index():
    ip = request.headers.get("X-Appengine-User-IP", request.environ.get('HTTP_X_REAL_IP', request.remote_addr))
    if ip:
        return jsonify({"IP": ip})
    return jsonify({'error':'no ip headers'})

class PyIP:
    def setup(self):
        self.register_blueprint(ip, url_prefix="/ip")
        #connect_event("after_navigation", hello_world)
```

**Comment by gnubyte** [comment]
Just out of curiosity, is your identifier in the info.json the same as the name of the folder?

**Comment by vladiuz1** [comment]
![Oct-18-2020 12-44-25](https://user-images.githubusercontent.com/22708849/96363898-b7d91080-113f-11eb-8ac1-8ab087732da3.gif)

info.json:
```json
{
    "identifier": "my_ip",
    "name": "PyIP",
    "author": "vladiuz1",
    "license": "MIT",
    "description": "This plugin adds a /my-ip endpoint that shows the ip.",
    "version": "1.0.0"
}

```

**Comment by vladiuz1** [comment]
No idea where to look? I tried installing again from scratch, same thing. even removed all the extra dependancies. May be something to do with python version? Or system (OSX).

Python 3.7.1


```
$ python3 app.py 

Traceback (most recent call last):
  File "app.py", line 13, in <module>
    plugin_manager.init_app(app)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_plugins/__init__.py", line 245, in init_app
    self.setup_plugins()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_plugins/__init__.py", line 331, in setup_plugins
    for plugin in itervalues(self.plugins):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_plugins/__init__.py", line 259, in plugins
    self.load_plugins()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_plugins/__init__.py", line 269, in load_plugins
    for plugin_name, plugin_package in iteritems(self.find_plugins()):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_plugins/__init__.py", line 306, in find_plugins
    tmp = importlib.import_module(plugin)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'test1'

```

**Comment by vladiuz1** [comment]
@gnubyte any idea at all? What do you suggest I try?

**Comment by sh4nks** [comment]
Without a fully reproducible example it's going to be hard to debug this issue. Could you provide us such an example?

**Comment by vladiuz1** [comment]
```
git clone git@github.com:vladiuz1/flask-plugins-test.git
```

**Comment by vladiuz1** [comment]
@sh4nks , @gnubyte does the script in the repo work for you?

**Comment by vladiuz1** [comment]
$$$
150.00
$$$

I have posted a bounty for this ticket:

https://www.bountysource.com/issues/93720599-modulenotfounderror-no-module-named-testapp

**Comment by gnubyte** [comment]
Hey Vlad, sorry for not getting back to you sooner I've been swamped. Save the $150 or if it attracts some more help, that is always great.

Taking a look now at this.

**Comment by gnubyte** [comment]
My assessment based on my environment:
 - `pip 20.2.2 from /usr/local/lib/python3.8/site-packages/pip (python 3.8)`
 - `Python 3.8.5`

Reproduced the issue then got the demo code working. It mostly has to do with what global environments you had set in your bash/powershell environment, then a few other issues with inheriting the AppPlugin object. A full repo is now available with working code. I encourage you to take a look at the git commit to see specifically what changes I made.

https://github.com/gnubyte/flaskplugintest

![image](https://user-images.githubusercontent.com/16541000/97676796-8fb6af00-1a67-11eb-982d-9458fc45a2ac.png)


**Fix:**
1. an `AppPlugin`object must be available and inherited by the Plugin's class. This is what registers a `flask.blueprint` to the Flask app.
2. The environment variables for flask must be set as of flask 1.1.x

To quote the flask documentation found [here](https://flask.palletsprojects.com/en/1.1.x/quickstart/) they describe some of the changes. TLDR is that we used to use the `if __name__ == "__main__"` and the team behind flask is trying to get away from that style of deployment.

>The FLASK_APP environment variable is the name of the module to import at flask run. In case that module is incorrectly named you will get an import error upon start (or if debug is enabled when you navigate to the application). It will tell you what it tried to import and why it failed. The most common reason is a typo or because you did not actually create an app object.

`FLASK_APP=app.py flask run`

**Comment by vladiuz1** [comment]
@gnubyte 

Thank you very much! This fixed it. I guess my fault that I didn't pay attention to examples.

And now I feel like I insulted you by offering bounty ) You can stop this by accepting it, take it as a lunch on me )

**Comment by gnubyte** [comment]
Glad to hear we could help, and no insult taken! I've been there before too. The new flask env approach isn't particularly my favorite.
Thank you for using flask-plugins and feel free to ask for features or create issues for help, and we're always looking for more collaborators.

I sent an email to the Support team at bountysource to have them refund your bug bounty back to you. Cheers!
